language: rust
rust: stable
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.rustup
before_cache:
  - rm -rf /home/travis/.cargo/registry
before_install:
  - rustup component add clippy rustfmt
  - cargo clippy --version
  - cargo fmt --version
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo fmt -- --check
  - cargo clippy --all-features -- -D warnings