language: rust
rust: stable
cache: cargo
before_install:
  - rustup component add clippy rustfmt
  - cargo clippy --version
  - cargo fmt --version
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo fmt -- --check
  - cargo clippy --all-features -- -D warnings