name: deploy
on:
  push:
    branches: [master]
    tags: [v*]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AUTODEPLOY_URL: ${{ secrets.AUTODEPLOY_URL }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      REGISTRY_URI: "gnosispm/etherbalance"
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Develop
        if: github.ref == 'refs/heads/master'
        run: bash docker/deploy.sh master
      - name: Deploy Tag
        if: startsWith(github.ref, 'refs/tags/')
        run: bash docker/deploy.sh ${GITHUB_REF##*/}
