name: deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AUTODEPLOY_TAG: master
      DOCKERHUB_PROJECT: etherbalance
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - run: docker/deploy.sh $AUTODEPLOY_TAG
