name: deploy
on:
  push:
    branches: [master]
    tags: [v*]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AUTODEPLOY_TAG: develop
      AUTODEPLOY_URL: ${{ secrets.AUTODEPLOY_URL }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      REGISTRY_URI: "gnosispm/etherbalance"
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: bash docker/deploy.sh ${GITHUB_REF##*/}
